### ISSUE TITLE
Seminar 관련 Domain 구성 확인

### ISSUE THREAD

**Issue by seoilhyun** [ctb-wic/wic-site#31]
Seminar Domain 구성 확인

1. Attendance, TopicCandidate 는 Seminar에서 사용이라 동일 패키지에 구현
2. Enum class의 패키지 위치 확인이 필요

**Comment by ctb-wic** [comment]
seminar 패키지 하위에 seminar 패키지가 반복되어 이름을 event로 변경합니다.

**Comment by ctb-wic** [comment]
@seoilhyun  enum 내에 code와 description은 용도가 무엇인가요?

code가 코드화의 목적이라면, enum 이름 자체를 사용하면 될 것으로 보입니다.

description이 한글화가 목적이라면, resource bundle을 사용하면 될 것으로 보입니다.

리팩토링하면서 제거했는데 용도가 있으면 다시 되돌려놓도록 하겠습니다.

확인 부탁드립니다.
